language: csharp
solution: SQLTableClassGenerator.sln
mono: none
dotnet: 1.0.0-preview2-003131
os: osx

before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
install:
  - mono .nuget/nuget.exe restore SQLTableClassGenerator.sln -Verbosity detailed