language: csharp
solution: SQLTableClassGenerator.sln
sudo: required

before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
install:
  - mono .nuget/nuget.exe restore SQLTableClassGenerator.sln -Verbosity detailed